version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - codecalm
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@popperjs/core"
    versions:
    - 2.8.6
  - dependency-name: critical
    versions:
    - 3.0.0
  - dependency-name: rollup
    versions:
    - 2.38.2
    - 2.40.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
  - dependency-name: litepicker
    versions:
    - 2.0.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.1
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: apexcharts
    versions:
    - 3.24.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
  - dependency-name: browser-sync
    versions:
    - 2.26.14
